### ISSUE TITLE
[FE] sideMenu 상태 관리

### ISSUE THREAD

**Issue by LeeMir** [Wallet-expedition/MODIMOA#42]
- sideMenu를 redux로 상태관리 중인데, sideMenu를 연 후(true), 링크를 통해 다른 페이지로 이동하면 sideMenu는 닫히지만 상태는 여전히 true임
  - sideMenu를 열고 다른 창으로 이동한 뒤, 상품 리스트 페이지에서 마트 목록을 열면 sideMenu가 열림으로 인식되어있기 때문에 닫는 버튼이 비활성화 됨

TODO : 링크로 이동할 때 false로 바꾸기

**Comment by poiu694** [comment]
사이드 메뉴 상태관리 완료.
