### ISSUE TITLE
[FE] 상품 상세페이지 상태관리 Issue 새로고침

### ISSUE THREAD

**Issue by poiu694** [Wallet-expedition/MODIMOA#44]
상품 상세 페이지에서 새로고침 시 기존 Redux에 저장되어있던 상품이 날라가는 Issue 발견

TODO : Redux-persist의 도입 등, 상태관리 Issue를 해결하는 방안이 필요.

**Comment by LeeMir** [comment]
상세 페이지 작업할 때 TODO로 적어놓긴 했어요!  (ProductDetailContainer.js)
```
...
const item = useSelector((state) => state.productReducer.product);
  /* TODO : store와 url끝의 martid가 일치하지 않을 경우, API 호출해서 갱신 */
  let sale_percent = Math.round((item.sale_price * 100) / item.original_price);
...
```
이렇게 생각했던 이유는, 사용자가 새로고침뿐만 아니라 처음부터 martid가 붙은 상세 페이지 url로 한번에 접근하면 상태를 저장해 놓는다고 해도 의미가 없어질 것 같아서였어용
그런데 새로 고침은 Redux-persist를 사용하고 위와 같은 경우는 상세 페이지 -> 리스트 페이지로 redirect하는 방법도 괜찮을 것 같네요!!

**Comment by poiu694** [comment]
> 처음부터 martid가 붙은 상세 페이지 url로 한번에 접근하면 상태를 저장해 놓는다고 해도 의미가 없어질 것 같아서였어용
- 링크에 직접 접근하는 경우도 있네요 ㅠ

- 새로고침 및 직접 링크는 어떤 점이 편의가 좋은지에 대해 생각하는 방안이 나뉠 수도 있을 것 같은데, 모두의 의견을 수렴하는게 좋을 것 같아서 회의 안건으로 올리겠습니다!
------
 - 다시 생각해보니, 이거 둘 다 API를 활용하면 해결되니까 TODO대로 하는게 좋을 것 같습니다!
 - TODO대로 하고, 완료되면 Issue닫는 것으로 하겠습니다!

**Comment by poiu694** [comment]
API 호출과 함께 이슈 해결
