### ISSUE TITLE
Wiki에 회의록 옮기기

### ISSUE THREAD

**Issue by LeeMir** [Wallet-expedition/MODIMOA#75]
## 개요(기능에 대한 설명, 왜 필요한 지)

Notion 블록 스토리지가 가득 참에 따라 옮길 필요성이 생김

## TODO List

- [x] Notion => Wiki로 옮기기

**Comment by suin0730** [comment]
회의록 옮겼습니다!
![image](https://user-images.githubusercontent.com/43488326/149294703-ee589e8e-4d0a-4fb4-b14d-ce10a379d970.png)
